### ISSUE TITLE
Routing Doesn't Work

### ISSUE THREAD

**Issue by m-sterspace** [staticwebdev/nextjs-starter#6]
Routing doesn't work in this example when deployed on static web apps. 

There is no `routes.json` file, so no matter what url you enter into the address bar, it will always serve you with the main index.html homepage.

**Comment by fhinkel** [comment]
Hi there 👋 . Thanks for opening an issue. We made some changes to the app and routing works fine now on the deployed app (`/project/sveltejs-svelte`, `/`, `project/vuejs-vue`, ...). I'm going to close this issue.
