### ISSUE TITLE
Doesn't Use Static Site Generation

### ISSUE THREAD

**Issue by m-sterspace** [staticwebdev/nextjs-starter#7]
This doesn't use Next.js export functionality which produces a statically generated site like Gatsby.js.

I could be wrong but it seems like the predominant use case for combining Next.js with Azure Static Web Apps, would be if you were using Next export to generate a static site.

**Comment by alexgagnon** [comment]
Yeah it's seems like it's close, we can define the 'out' dir as the place to pull the output of `next export`, but only `next build` is being run.

**Comment by alexgagnon** [comment]
NVM, got it, seems the action provides an option to specific the build command, got it to work with the following:

```
          output_location: "out" # Built app content directory -
          app_build_command: "npx next build && npx next export"
```
